# # Minimal Nixpacks config - Railway will handle everything
# Just tell it this is a Python project

providers = []

[start]
cmd = "./start.sh"ation for Pattern Detection API
# Railway Root Directory should be set to: python
# Nixpacks Config File should be set to: ../nixpacks-pattern.toml

[phases.setup]
nixPkgs = ["python312", "gcc", "g++", "python312Packages.setuptools"]

[phases.install]
cmds = [
    "pip install --upgrade pip setuptools wheel",
    "pip install -r requirements-ml.txt"
]

[phases.build]
cmds = ["chmod +x start.sh"]

[start]
cmd = "./start.sh"
