# Nixpacks configuration for Pattern Detection API
# Railway Root Directory should be set to: python
# Nixpacks Config File should be set to: ../nixpacks-pattern.toml

[phases.setup]
nixPkgs = ["python312", "gcc", "g++", "python312Packages.setuptools"]

[phases.install]
cmds = [
    "pip install --upgrade pip setuptools wheel",
    "pip install -r requirements-ml.txt"
]

[phases.build]
cmds = []

[start]
cmd = "bash -c 'uvicorn pattern_detection_api:app --host 0.0.0.0 --port $PORT'"
