# Nixpacks configuration for CrewAI Service
[phases.setup]
nixPkgs = ["python312", "gcc", "pkg-config"]

[phases.install]
cmds = [
    "pip install --upgrade pip setuptools wheel",
    "pip install -r crewai-service/requirements.txt"
]

[phases.build]
cmds = ["echo 'CrewAI Service - Build complete'"]

[start]
cmd = "cd crewai-service && uvicorn main:app --host 0.0.0.0 --port $PORT"

[variables]
PYTHON_VERSION = "3.12"
