# Nixpacks configuration for Pattern Detection API
# Railway Root Directory should be set to: python
# Nixpacks Config File should be set to: ../nixpacks-pattern.toml

[phases.setup]
nixPkgs = ["python312", "gcc", "g++", "python312Packages.setuptools"]

[phases.install]
cmds = [
    "pip install --upgrade pip setuptools wheel"
]

[phases.build]
cmds = [
    "pip install -r requirements-ml.txt",
    "chmod +x start.sh"
]

[start]
cmd = "./start.sh"
