[phases.setup]
aptPkgs = ["python3", "python3-pip", "python3-dev"]

[phases.install]
cmds = [
    "curl -fsSL https://bun.sh/install | bash",
    "export PATH=\"$HOME/.bun/bin:$PATH\"",
    "pip install -r requirements.txt",
    "~/.bun/bin/bun install"
]

[phases.build]
cmds = ["~/.bun/bin/bun run build"]

[start]
cmd = "~/.bun/bin/bun start"