[phases.setup]
aptPkgs = ["python3", "python3-pip", "python3-venv", "curl"]

[phases.install]
cmds = [
    # Install Poetry
    "curl -sSL https://install.python-poetry.org | python3 -",
    "export PATH=\"$HOME/.local/bin:$PATH\"",
    # Install Bun
    "curl -fsSL https://bun.sh/install | bash",
    "export PATH=\"$HOME/.bun/bin:$PATH\"",
    # Install frontend dependencies
    "cd frontend && ~/.bun/bin/bun install",
    # Install Python dependencies
    "cd services && ~/.local/bin/poetry install --no-dev"
]

[phases.build]
cmds = [
    "export PATH=\"$HOME/.bun/bin:$PATH\"",
    "cd frontend && ~/.bun/bin/bun run build"
]

[start]
cmd = "export PATH=\"$HOME/.bun/bin:$PATH\" && export PATH=\"$HOME/.local/bin:$PATH\" && ~/.bun/bin/bun run start"