name: virtual_options_desk_mobile
description: Mobile candlestick chart viewer with AI enhancements for Virtual Options Desk
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI Components
  cupertino_icons: ^1.0.6
  
  # Candlestick Charts
  candlesticks: ^2.1.0
  fl_chart: ^0.66.0
  
  # State Management
  provider: ^6.1.1
  riverpod: ^2.4.9
  flutter_riverpod: ^2.4.9
  
  # HTTP & API
  http: ^1.2.0
  dio: ^5.4.0
  
  # Supabase Integration
  supabase_flutter: ^2.3.4
  
  # WebSocket for real-time data
  web_socket_channel: ^2.4.0
  
  # Data models & serialization
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  
  # Storage
  shared_preferences: ^2.2.2
  
  # Utilities
  intl: ^0.19.0
  logger: ^2.0.2+1
  
  # Environment variables
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^3.0.1
  
  # Code generation
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  freezed: ^2.4.6

flutter:
  uses-material-design: true
  
  # Add your assets here
  # assets:
  #   - images/
  #   - assets/
