[phases.setup]
nixPkgs = ["nodejs-20_x"]

[phases.install]
cmds = [
  "npm ci --include=dev"
]

[phases.build]
cmds = [
  "npm run build"
]

[phases.deploy]
cmds = [
  "npm prune --production",
  "node dist/index.js"
]

[start]
cmd = "node dist/index.js"

[variables]
NODE_ENV = "production"
