[phases.setup]
nixPkgs = ["nodejs-20_x"]

[phases.install]
cmds = [
  "npm ci --include=dev"
]

[phases.build]
cmds = [
  "npm run build"
]

[start]
cmd = "node --trace-warnings dist/index.js"

[variables]
NODE_ENV = "production"
PORT = "8080"
