[build]
builder = "NIXPACKS"

[build.env]
NODE_VERSION = "20"

[deploy]
startCommand = "npm run build && npm start"
healthcheckPath = "/health"
healthcheckTimeout = 10
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
